<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="DevelopmentTest.Default" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Home - DevelopmentTest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 0; background: #f7f9fc; color: #222; }
        .shell { max-width: 900px; margin: 0 auto; padding: 24px 24px 40px; }
        header { padding: 12px 0 16px; margin-bottom: 12px; }
        .app-title { font-size: 18px; font-weight: 600; margin: 0 0 4px; }
        .app-sub { font-size: 12px; color: #667; margin: 0; }
        nav { display: flex; gap: 12px; margin-bottom: 20px; }
        nav a { text-decoration: none; color: #0050b3; font-size: 14px; padding: 6px 10px; border-radius: 4px; }
        nav a:hover { background-color: #e6f2ff; }
        h1 { margin: 8px 0 4px; font-size: 22px; }
        p { margin: 4px 0 12px; }
        .card { background: #fff; border: 1px solid #dde3ee; border-radius: 6px; padding: 16px 18px; margin-top: 12px; }
        .card h2 { margin: 0 0 8px; font-size: 16px; }
        .card p { margin: 2px 0 6px; font-size: 13px; }
        .card a { color: #0050b3; text-decoration: none; }
        .card a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="shell">
            <header>
                <div class="app-title">WorkFlow</div>
            </header>
            <nav>
                <a href="Default.aspx">Home</a>
                <a href="SalesOrders.aspx">Sales Orders</a>
                <a href="AllInvoices.aspx">All Invoices</a>
                <a href="Invoices.aspx">Open Invoices</a>
                <a href="Payments.aspx">Payments</a>
                <a href="GLTransactions.aspx">GL Transactions</a>
            </nav>

            <div class="card">
                <h2>1. Sales Orders</h2>
                <p>Create a new order, add lines with quantities and prices, and then release the order to become an invoice.</p>
                <p><a href="SalesOrders.aspx">Go to Sales Orders</a></p>
            </div>

            <div class="card">
                <h2>2. Invoices</h2>
                <p>View all invoices with status, or post open invoices. Posting updates stock and creates GL entries for AR, Sales and VAT.</p>
                <p><a href="AllInvoices.aspx">All Invoices</a> &nbsp;|&nbsp; <a href="Invoices.aspx">Open Invoices</a></p>
            </div>

            <div class="card">
                <h2>3. Receive payment</h2>
                <p>Select a posted or partially paid invoice, enter the amount received. Invoice status becomes Paid/PartiallyPaid and GL is posted (Dr 1000 Cash, Cr 1100 AR).</p>
                <p><a href="Payments.aspx">Go to Payments</a></p>
            </div>

            <div class="card">
                <h2>4. GL transactions</h2>
                <p>View the GL entries generated by invoice posting and payments (Dr/Cr lines per transaction).</p>
                <p><a href="GLTransactions.aspx">Go to GL Transactions</a></p>
            </div>
        </div>
    </form>
</body>
</html>
